coverage:
  precision: 2
  round: down
  range: 60..80

ignore:
  - ".claude/**"
  - ".config/**"
  - ".cargo/**"
  - ".github/**"
  - ".vscode/**"
  - "assets/**"
  - "docs/**"
  - "flatpak/**"
  - "target/**"

  - "**/*.md"
  - "**/*.toml"
  - "**/*.yml"
  - "**/*.yaml"
  - "**/*.txt"
  - "LICENSE-APACHE"
  - "LICENSE-MIT"
  - "Dockerfile"

  - "crates/spz/tests/**"
  - "crates/spz/benches/**"
  - "crates/spz/examples/**"

  - "crates/spz-binding-python/tests/**"
  - "crates/spz-binding-python/examples/**"
  - "crates/spz-binding-python/benches/**"
  - "crates/spz-binding-python/pypkg/tests/**"

  - "crates/spz-binding-c/examples/**"
