coverage:
  precision: 2
  round: down
  range: 60..80

ignore:
  - ".claude"
  - ".config"
  - ".cargo"
  - ".github"
  - ".vscode"
  - "assets"
  - "docs"
  - "flatpak"
  - "target"

  - "*.md"
  - "*.toml"
  - "*.yml"
  - "*.yaml"
  - "*.txt"
  - "LICENSE-APACHE"
  - "LICENSE-MIT"
  - "Dockerfile"

  - "crates/spz/src/lib.rs"
  - "crates/spz/tests"
  - "crates/spz/benches"

  - "crates/spz-binding-python/src/lib.rs"
  - "crates/spz-binding-python/tests"
  - "crates/spz-binding-python/benches"
  - "crates/spz-binding-python/pypkg/tests"

  - "crates/spz-capi"
