coverage:
  precision: 2
  round: down
  range: 60..80

  ignore:
    - ".claude"
    - ".config"
    - ".cargo"
    - ".github"
    - ".vscode"
    - "assets"
    - "docs"
    - "flatpak"
    - "target"

    - "*.md"
    - "*.toml"
    - "*.yml"
    - "*.yaml"
    - "*.txt"
    - "LICENSE-APACHE"
    - "LICENSE-MIT"
    - "Dockerfile"

    - "crates/spz/src/lib.rs"
    - "crates/spz/tests/**"
    - "crates/spz/benches/**"

    - "crates/spz-pywrapper/src/lib.rs"
    - "crates/spz-pywrapper/tests"
    - "crates/spz-pywrapper/benches/**"
    - "crates/spz-pywrapper/pypkg/tests/**"

    - "crates/spz-capi/**"
